#!/usr/bin/env python3
"""
Volume Spike Scanner (3x MA10)
- Scan saham di UNIVERSE
- Deteksi saham yang volume hari ini >= 3x rata-rata volume 10 hari terakhir (MA10)
"""

import warnings
warnings.filterwarnings("ignore")

import io
import contextlib
import logging
from datetime import datetime

import numpy as np
import pandas as pd
import yfinance as yf

# =========================
# CONFIG
# =========================

# Pakai UNIVERSE yang sama dari script kamu:
# from your_other_script import UNIVERSE
# atau paste langsung di sini:
# UNIVERSE = [ ... ]

PERIOD_DAILY = "60d"   # cukup 60 hari kebelakang

logging.getLogger("yfinance").setLevel(logging.CRITICAL)

UNIVERSE = [
    "AALI.JK",
    "ABBA.JK",
    "ABDA.JK",
    "ABM.JK",
    "ABMM.JK",
    "ACES.JK",
    "ACRO.JK",
    "ACST.JK",
    "ADCP.JK",
    "ADES.JK",
    "ADHI.JK",
    "ADMF.JK", 
    "ADMG.JK",
    "ADMR.JK",
    "ADRO.JK",
    "AEGS.JK",
    "AGAR.JK",
    "AGII.JK",
    "AGRO.JK",
    "AGRS.JK",
    "AHAP.JK",
    "AIDX.JK",
    "AIMS.JK",
    "AISA.JK", 
    "AKKU.JK",
    "AKPI.JK",
    "AKR.JK",
    "AKRA.JK",
    "AKSI.JK",
    "ALDO.JK",
    "ALKA.JK",
    "ALMI.JK",
    "ALTO.JK",
    "AMAG.JK",
    "AMAN.JK",
    "AMAR.JK", 
    "AMFG.JK",
    "AMIN.JK",
    "AMMN.JK",
    "AMMS.JK",
    "AMOR.JK",
    "AMRT.JK",
    "ANDI.JK",
    "ANJT.JK",
    "ANTM.JK",
    "APEX.JK",
    "APIC.JK",
    "APII.JK", 
    "APLI.JK",
    "APLN.JK",
    "APSI.JK",
    "ARCI.JK",
    "AREA.JK",
    "ARGO.JK",
    "ARII.JK",
    "ARKA.JK",
    "ARKO.JK",
    "ARMY.JK",
    "ARNA.JK",
    "ARTA.JK", 
    "ARTI.JK",
    "ARTO.JK",
    "ASBI.JK",
    "ASDM.JK",
    "ASE.JK",
    "ASGR.JK",
    "ASHA.JK",
    "ASIA.JK",
    "ASII.JK",
    "ASJT.JK",
    "ASLC.JK",
    "ASLI.JK", 
    "ASMI.JK",
    "ASPI.JK",
    "ASRI.JK",
    "ASRM.JK",
    "ASSA.JK",
    "ATAP.JK",
    "ATIC.JK",
    "ATLA.JK",
    "AVIA.JK",
    "AWAN.JK",
    "AXIO.JK",
    "AYAM.JK", 
    "AYLS.JK",
    "BABP.JK",
    "BABY.JK",
    "BACA.JK",
    "BAIK.JK",
    "BAJA.JK",
    "BALI.JK",
    "BAPA.JK",
    "BAPI.JK",
    "BATA.JK",
    "BATR.JK",
    "BAUT.JK", 
    "BAYU.JK",
    "BBCA.JK",
    "BBHI.JK",
    "BBKP.JK",
    "BBLD.JK",
    "BBMD.JK",
    "BBNI.JK",
    "BBRI.JK",
    "BBRM.JK",
    "BBSI.JK",
    "BBSS.JK",
    "BBTN.JK", 
    "BBYB.JK",
    "BCAP.JK",
    "BCIC.JK",
    "BCIP.JK",
    "BDKR.JK",
    "BDMN.JK",
    "BEBS.JK",
    "BEEF.JK",
    "BEI.JK",
    "BEKS.JK",
    "BELI.JK",
    "BELL.JK", 
    "BESS.JK",
    "BEST.JK",
    "BFI.JK",
    "BFIN.JK",
    "BGTG.JK",
    "BHAT.JK",
    "BHIT.JK",
    "BIKA.JK",
    "BIKE.JK",
    "BIMA.JK",
    "BINA.JK",
    "BINO.JK", 
    "BIPI.JK",
    "BIPP.JK",
    "BIRD.JK",
    "BISI.JK",
    "BIST.JK",
    "BJBR.JK",
    "BJTM.JK",
    "BKDP.JK",
    "BKSL.JK",
    "BKSW.JK",
    "BLES.JK",
    "BLTA.JK", 
    "BLTZ.JK",
    "BLUE.JK",
    "BMAS.JK",
    "BMBL.JK",
    "BMHS.JK",
    "BMRI.JK",
    "BMSR.JK",
    "BMTR.JK",
    "BNBA.JK",
    "BNBR.JK",
    "BNGA.JK",
    "BNII.JK", 
    "BNLI.JK",
    "BOBA.JK",
    "BOGA.JK",
    "BOLA.JK",
    "BOLT.JK",
    "BOSS.JK",
    "BPFI.JK",
    "BPII.JK",
    "BPTR.JK",
    "BRAM.JK",
    "BRIS.JK",
    "BRMS.JK", 
    "BRNA.JK",
    "BRPT.JK",
    "BSBK.JK",
    "BSDE.JK",
    "BSE.JK",
    "BSIM.JK",
    "BSML.JK",
    "BSSR.JK",
    "BSWD.JK",
    "BTEK.JK",
    "BTEL.JK",
    "BTON.JK", 
    "BTPN.JK",
    "BTPS.JK",
    "BUAH.JK",
    "BUDI.JK",
    "BUKA.JK",
    "BUKK.JK",
    "BULL.JK",
    "BUMI.JK",
    "BUVA.JK",
    "BVIC.JK",
    "BWPT.JK",
    "BYAN.JK", 
    "CAKK.JK",
    "CAMP.JK",
    "CANI.JK",
    "CARE.JK",
    "CARS.JK",
    "CASA.JK",
    "CASH.JK",
    "CASS.JK",
    "CBMF.JK",
    "CBP.JK",
    "CBPE.JK",
    "CBRE.JK", 
    "CBUT.JK",
    "CCSI.JK",
    "CEKA.JK",
    "CENT.JK",
    "CFIN.JK",
    "CGAS.JK",
    "CHEM.JK",
    "CHIP.JK",
    "CIMB.JK",
    "CINT.JK",
    "CITA.JK",
    "CITY.JK", 
    "CLAY.JK",
    "CLEO.JK",
    "CLPI.JK",
    "CMNP.JK",
    "CMNT.JK",
    "CMPP.JK",
    "CMRY.JK",
    "CNBC.JK",
    "CNKO.JK",
    "CNMA.JK",
    "CNN.JK",
    "CNTX.JK", 
    "COAL.JK",
    "COCO.JK",
    "COWL.JK",
    "CPIN.JK",
    "CPRI.JK",
    "CPRO.JK",
    "CPU.JK",
    "CRAB.JK",
    "CRSN.JK",
    "CSAP.JK",
    "CSI.JK",
    "CSIS.JK", 
    "CSMI.JK",
    "CSRA.JK",
    "CTBN.JK",
    "CTRA.JK",
    "CTTH.JK",
    "CUAN.JK",
    "CYBR.JK",
    "DADA.JK",
    "DART.JK",
    "DATA.JK",
    "DAYA.JK",
    "DCI.JK", 
    "DCII.JK",
    "DEAL.JK",
    "DEFI.JK",
    "DEPO.JK",
    "DEWA.JK",
    "DEWI.JK",
    "DFAM.JK",
    "DFM.JK",
    "DGIK.JK",
    "DGNS.JK",
    "DIGI.JK",
    "DILD.JK", 
    "DIVA.JK",
    "DKFT.JK",
    "DLTA.JK",
    "DMAS.JK",
    "DMMX.JK",
    "DMND.JK",
    "DMS.JK",
    "DNAR.JK",
    "DNET.JK",
    "DOID.JK",
    "DOOH.JK",
    "DOSS.JK", 
    "DPNS.JK",
    "DPUM.JK",
    "DRMA.JK",
    "DSE.JK",
    "DSFI.JK",
    "DSNG.JK",
    "DSSA.JK",
    "DUCK.JK",
    "DUTI.JK",
    "DVLA.JK",
    "DWGL.JK",
    "DYAN.JK", 
    "EAST.JK",
    "ECII.JK",
    "EDGE.JK",
    "EJKSE.JK",
    "EKAD.JK",
    "ELIT.JK",
    "ELPI.JK",
    "ELSA.JK",
    "ELTY.JK",
    "EMDE.JK",
    "EMTK.JK",
    "ENAK.JK", 
    "ENRG.JK",
    "ENVY.JK",
    "ENZO.JK",
    "EPAC.JK",
    "EPMT.JK",
    "ERAA.JK",
    "ERAL.JK",
    "ERTX.JK",
    "ESIP.JK",
    "ESSA.JK",
    "ESTA.JK",
    "ESTI.JK", 
    "ETWA.JK",
    "EURO.JK",
    "EXCL.JK",
    "FAP.JK",
    "FAPA.JK",
    "FAST.JK",
    "FASW.JK",
    "FIDX.JK",
    "FILM.JK",
    "FIMP.JK",
    "FIRE.JK",
    "FISH.JK", 
    "FITT.JK",
    "FKS.JK",
    "FKX.JK",
    "FLMC.JK",
    "FMII.JK",
    "FOLK.JK",
    "FORU.JK",
    "FORZ.JK",
    "FPNI.JK",
    "FREN.JK",
    "FUJI.JK",
    "FUTR.JK", 
    "FWCT.JK",
    "GAMA.JK",
    "GDST.JK",
    "GDYR.JK",
    "GEH.JK",
    "GEL.JK",
    "GEMA.JK",
    "GEMS.JK",
    "GES.JK",
    "GET.JK",
    "GGRM.JK",
    "GGRP.JK", 
    "GHON.JK",
    "GIAA.JK",
    "GIFT.JK",
    "GJTL.JK",
    "GLOB.JK",
    "GLVA.JK",
    "GMFI.JK",
    "GMTD.JK",
    "GOLD.JK",
    "GOLF.JK",
    "GOLL.JK",
    "GOOD.JK", 
    "GOTO.JK",
    "GPRA.JK",
    "GPSO.JK",
    "GRIA.JK",
    "GRPH.JK",
    "GRPM.JK",
    "GSMF.JK",
    "GTBO.JK",
    "GTS.JK",
    "GTSI.JK",
    "GULA.JK",
    "GUNA.JK", 
    "GWSA.JK",
    "GZCO.JK",
    "HADE.JK",
    "HAIS.JK",
    "HAJJ.JK",
    "HALO.JK",
    "HATM.JK",
    "HBAT.JK",
    "HDFA.JK",
    "HDIT.JK",
    "HDTX.JK",
    "HEAL.JK", 
    "HELI.JK",
    "HERO.JK",
    "HEXA.JK",
    "HITS.JK",
    "HKMU.JK",
    "HMSP.JK",
    "HOKI.JK",
    "HOME.JK",
    "HOMI.JK",
    "HOPE.JK",
    "HOTL.JK",
    "HRME.JK", 
    "HRTA.JK",
    "HRUM.JK",
    "HUMI.JK",
    "HYGN.JK",
    "IATA.JK",
    "IBFN.JK",
    "IBK.JK",
    "IBOS.JK",
    "IBST.JK",
    "ICBP.JK",
    "ICON.JK",
    "ICTSI.JK", 
    "IDEA.JK",
    "IDPR.JK",
    "IFII.JK",
    "IFSH.JK",
    "IGAR.JK",
    "IIKP.JK",
    "IKAI.JK",
    "IKAN.JK",
    "IKBI.JK",
    "IKPM.JK",
    "IMAS.JK",
    "IMC.JK", 
    "IMJS.JK",
    "IMPC.JK",
    "INAF.JK",
    "INAI.JK",
    "INCF.JK",
    "INCI.JK",
    "INCO.JK",
    "IND.JK",
    "INDEX.JK",
    "INDF.JK",
    "INDR.JK",
    "INDS.JK", 
    "INDX.JK",
    "INDY.JK",
    "INET.JK",
    "INKP.JK",
    "INOV.JK",
    "INPC.JK",
    "INPP.JK",
    "INPS.JK",
    "INRU.JK",
    "INTA.JK",
    "INTD.JK",
    "INTP.JK", 
    "IOTF.JK",
    "IPAC.JK",
    "IPCC.JK",
    "IPCM.JK",
    "IPOL.JK",
    "IPPE.JK",
    "IPTV.JK",
    "IRRA.JK",
    "IRSX.JK",
    "ISAP.JK",
    "ISAT.JK",
    "ISBN.JK", 
    "ISSI.JK",
    "ISSP.JK",
    "ITIC.JK",
    "ITMA.JK",
    "ITMG.JK",
    "ITSEC.JK",
    "JARR.JK",
    "JAST.JK",
    "JATI.JK",
    "JAWA.JK",
    "JECC.JK",
    "JGLE.JK", 
    "JIHD.JK",
    "JKON.JK",
    "JKSW.JK",
    "JMAS.JK",
    "JPFA.JK",
    "JRPT.JK",
    "JSKY.JK",
    "JSMR.JK",
    "JSPT.JK",
    "JSX.JK",
    "JTPE.JK",
    "KAEF.JK", 
    "KARW.JK",
    "KASE.JK",
    "KAYU.JK",
    "KBAG.JK",
    "KBLI.JK",
    "KBLM.JK",
    "KBLV.JK",
    "KBRI.JK",
    "KDB.JK",
    "KDSI.JK",
    "KDTN.JK",
    "KEEN.JK", 
    "KEJU.JK",
    "KETR.JK",
    "KIAS.JK",
    "KICI.JK",
    "KIJA.JK",
    "KING.JK",
    "KINO.JK",
    "KIOS.JK",
    "KJEN.JK",
    "KKES.JK",
    "KKGI.JK",
    "KLAS.JK", 
    "KLBF.JK",
    "KLCI.JK",
    "KLIN.JK",
    "KMDS.JK",
    "KMI.JK",
    "KMTR.JK",
    "KOBX.JK",
    "KOCI.JK",
    "KOIN.JK",
    "KOKA.JK",
    "KONI.JK",
    "KOPI.JK", 
    "KOSPI.JK",
    "KPAL.JK",
    "KPAS.JK",
    "KPIG.JK",
    "KRAH.JK",
    "KRAS.JK",
    "KREN.JK",
    "KRYA.JK",
    "KSE.JK",
    "KUAS.JK",
    "LABA.JK",
    "LABS.JK", 
    "LAJU.JK",
    "LAND.JK",
    "LAPD.JK",
    "LCGP.JK",
    "LCK.JK",
    "LCKM.JK",
    "LEAD.JK",
    "LFLO.JK",
    "LIFE.JK",
    "LINK.JK",
    "LION.JK",
    "LIVE.JK", 
    "LMAS.JK",
    "LMAX.JK",
    "LMPI.JK",
    "LMSH.JK",
    "LOPI.JK",
    "LPCK.JK",
    "LPGI.JK",
    "LPIN.JK",
    "LPKR.JK",
    "LPLI.JK",
    "LPPF.JK",
    "LPPS.JK", 
    "LRNA.JK",
    "LSIP.JK",
    "LTLS.JK",
    "LUCK.JK",
    "LUCY.JK",
    "MABA.JK",
    "MAGP.JK",
    "MAHA.JK",
    "MAIN.JK",
    "MAMI.JK",
    "MANG.JK",
    "MAP.JK", 
    "MAPA.JK",
    "MAPB.JK",
    "MAPI.JK",
    "MARI.JK",
    "MARK.JK",
    "MASA.JK",
    "MASB.JK",
    "MAXI.JK",
    "MAYA.JK",
    "MBAP.JK",
    "MBMA.JK",
    "MBSS.JK", 
    "MBTO.JK",
    "MCAS.JK",
    "MCOL.JK",
    "MCOR.JK",
    "MDIA.JK",
    "MDKA.JK",
    "MDKI.JK",
    "MDLN.JK",
    "MDRN.JK",
    "MEDC.JK",
    "MEDS.JK",
    "MEGA.JK", 
    "MEJA.JK",
    "MENN.JK",
    "MERK.JK",
    "META.JK",
    "MFD.JK",
    "MFIN.JK",
    "MFMI.JK",
    "MGLV.JK",
    "MGNA.JK",
    "MGRO.JK",
    "MHKI.JK",
    "MICE.JK", 
    "MIDI.JK",
    "MIKA.JK",
    "MINA.JK",
    "MIRA.JK",
    "MITI.JK",
    "MKAP.JK",
    "MKNT.JK",
    "MKPI.JK",
    "MKTR.JK",
    "MLBI.JK",
    "MLIA.JK",
    "MLPL.JK", 
    "MLPT.JK",
    "MMIX.JK",
    "MMLP.JK",
    "MNC.JK",
    "MNCN.JK",
    "MOLI.JK",
    "MORA.JK",
    "MPIX.JK",
    "MPMX.JK",
    "MPOW.JK",
    "MPPA.JK",
    "MPRO.JK", 
    "MPX.JK",
    "MPXL.JK",
    "MRAT.JK",
    "MREI.JK",
    "MSIE.JK",
    "MSIG.JK",
    "MSIN.JK",
    "MSJA.JK",
    "MSKY.JK",
    "MSTI.JK",
    "MTDL.JK",
    "MTEL.JK", 
    "MTFN.JK",
    "MTLA.JK",
    "MTMH.JK",
    "MTPS.JK",
    "MTRA.JK",
    "MTSM.JK",
    "MTWI.JK",
    "MUTU.JK",
    "MYOH.JK",
    "MYOR.JK",
    "MYRX.JK",
    "MYTX.JK", 
    "NANO.JK",
    "NASA.JK",
    "NASI.JK",
    "NATO.JK",
    "NAYZ.JK",
    "NELY.JK",
    "NEST.JK",
    "NETV.JK",
    "NFC.JK",
    "NFCX.JK",
    "NICE.JK",
    "NICK.JK", 
    "NICL.JK",
    "NIFTY.JK",
    "NIKL.JK",
    "NINE.JK",
    "NIPS.JK",
    "NIRO.JK",
    "NISP.JK",
    "NOBU.JK",
    "NPGF.JK",
    "NRCA.JK",
    "NTBK.JK",
    "NUSA.JK", 
    "NZIA.JK",
    "OASA.JK",
    "OBM.JK",
    "OBMD.JK",
    "OCAP.JK",
    "OCBC.JK",
    "OILS.JK",
    "OKAS.JK",
    "OLIV.JK",
    "OMED.JK",
    "OMRE.JK",
    "OPMS.JK", 
    "PACK.JK",
    "PADA.JK",
    "PADI.JK",
    "PALM.JK",
    "PAM.JK",
    "PAMG.JK",
    "PANI.JK",
    "PANR.JK",
    "PANS.JK",
    "PBID.JK",
    "PBRX.JK",
    "PBSA.JK", 
    "PCAR.JK",
    "PDES.JK",
    "PDPP.JK",
    "PEGE.JK",
    "PEHA.JK",
    "PEVE.JK",
    "PGAS.JK",
    "PGEO.JK",
    "PGJO.JK",
    "PGLI.JK",
    "PGUN.JK",
    "PICO.JK", 
    "PIPA.JK",
    "PJAA.JK",
    "PKPK.JK",
    "PLAN.JK",
    "PLAS.JK",
    "PLIN.JK",
    "PMJS.JK",
    "PMMP.JK",
    "PNBN.JK",
    "PNBS.JK",
    "PNGO.JK",
    "PNIN.JK", 
    "PNLF.JK",
    "PNSE.JK",
    "POLA.JK",
    "POLI.JK",
    "POLL.JK",
    "POLU.JK",
    "POLY.JK",
    "POOL.JK",
    "PORT.JK",
    "POSA.JK",
    "POWR.JK",
    "PPGL.JK", 
    "PPRE.JK",
    "PPRI.JK",
    "PPRO.JK",
    "PRAS.JK",
    "PRAY.JK",
    "PRDA.JK",
    "PRIM.JK",
    "PSAB.JK",
    "PSDN.JK",
    "PSE.JK",
    "PSGO.JK",
    "PSKT.JK", 
    "PSSI.JK",
    "PTBA.JK",
    "PTDU.JK",
    "PTIS.JK",
    "PTMP.JK",
    "PTMR.JK",
    "PTPP.JK",
    "PTPS.JK",
    "PTPW.JK",
    "PTRO.JK",
    "PTSN.JK",
    "PTSP.JK", 
    "PUDP.JK",
    "PURA.JK",
    "PURE.JK",
    "PURI.JK",
    "PWON.JK",
    "PYFA.JK",
    "PZZA.JK",
    "QNB.JK",
    "RAAM.JK",
    "RAFI.JK",
    "RAJA.JK",
    "RALS.JK", 
    "RANC.JK",
    "RBMS.JK",
    "RCCC.JK",
    "RCR.JK",
    "RDTX.JK",
    "REAL.JK",
    "RELF.JK",
    "RELI.JK",
    "RGAS.JK",
    "RICY.JK",
    "RIGS.JK",
    "RIMO.JK", 
    "RISE.JK",
    "RLQ.JK",
    "RMBA.JK",
    "RMK.JK",
    "RMKE.JK",
    "ROCK.JK",
    "RODA.JK",
    "RONY.JK",
    "ROTI.JK",
    "RSCH.JK",
    "RSGK.JK",
    "RUIS.JK", 
    "RUNS.JK",
    "SAFE.JK",
    "SAGE.JK",
    "SAME.JK",
    "SAMF.JK",
    "SAPX.JK",
    "SATU.JK",
    "SBAT.JK",
    "SBMA.JK",
    "SCCO.JK",
    "SCMA.JK",
    "SCNP.JK", 
    "SCPI.JK",
    "SDMU.JK",
    "SDPC.JK",
    "SDRA.JK",
    "SEMA.JK",
    "SET.JK",
    "SFAN.JK",
    "SGER.JK",
    "SGRO.JK",
    "SHID.JK",
    "SHIP.JK",
    "SICO.JK", 
    "SIDO.JK",
    "SILO.JK",
    "SIMA.JK",
    "SIMP.JK",
    "SINI.JK",
    "SIPD.JK",
    "SKBM.JK",
    "SKLT.JK",
    "SKRN.JK",
    "SKYB.JK",
    "SLIS.JK",
    "SLJ.JK", 
    "SMAR.JK",
    "SMBR.JK",
    "SMCB.JK",
    "SMDM.JK",
    "SMDR.JK",
    "SMGA.JK",
    "SMGR.JK",
    "SMIL.JK",
    "SMKL.JK",
    "SMKM.JK",
    "SMLE.JK",
    "SMMA.JK", 
    "SMMT.JK",
    "SMR.JK",
    "SMRA.JK",
    "SMRU.JK",
    "SMSM.JK",
    "SNLK.JK",
    "SOCI.JK",
    "SOFA.JK",
    "SOHO.JK",
    "SOLA.JK",
    "SONA.JK",
    "SOSS.JK", 
    "SOTS.JK",
    "SOUL.JK",
    "SPMA.JK",
    "SPRE.JK",
    "SPTO.JK",
    "SQMI.JK",
    "SRAJ.JK",
    "SRIL.JK",
    "SRSN.JK",
    "SRTG.JK",
    "SSE.JK",
    "SSIA.JK", 
    "SSMS.JK",
    "SSTM.JK",
    "STAA.JK",
    "STAR.JK",
    "STI.JK",
    "STTP.JK",
    "SUGI.JK",
    "SULI.JK",
    "SUNI.JK",
    "SUPR.JK",
    "SURE.JK",
    "SURI.JK", 
    "SWAT.JK",
    "SWID.JK",
    "SZSE.JK",
    "TAIEX.JK",
    "TALF.JK",
    "TAMU.JK",
    "TAPG.JK",
    "TARA.JK",
    "TASI.JK",
    "TAXI.JK",
    "TAYS.JK",
    "TBIG.JK", 
    "TBLA.JK",
    "TBMS.JK",
    "TBS.JK",
    "TCID.JK",
    "TCPI.JK",
    "TDPM.JK",
    "TEBE.JK",
    "TECH.JK",
    "TELE.JK",
    "TFAS.JK",
    "TFCO.JK",
    "TGKA.JK", 
    "TGRA.JK",
    "TGUK.JK",
    "TIFA.JK",
    "TINS.JK",
    "TIRA.JK",
    "TIRT.JK",
    "TKIM.JK",
    "TLDN.JK",
    "TLKM.JK",
    "TMAS.JK",
    "TMPO.JK",
    "TNCA.JK", 
    "TOBA.JK",
    "TOOL.JK",
    "TOPIX.JK",
    "TOPS.JK",
    "TOSK.JK",
    "TOTL.JK",
    "TOTO.JK",
    "TOWR.JK",
    "TOYS.JK",
    "TPIA.JK",
    "TPMA.JK",
    "TRAM.JK", 
    "TRGU.JK",
    "TRIL.JK",
    "TRIM.JK",
    "TRIN.JK",
    "TRIO.JK",
    "TRIS.JK",
    "TRJA.JK",
    "TRON.JK",
    "TRST.JK",
    "TRUE.JK",
    "TRUK.JK",
    "TRUS.JK", 
    "TSE.JK",
    "TSPC.JK",
    "TUGU.JK",
    "TURI.JK",
    "TYRE.JK",
    "UANG.JK",
    "UBC.JK",
    "UCID.JK",
    "UDNG.JK",
    "UFOE.JK",
    "ULS.JK",
    "ULSP.JK", 
    "ULTJ.JK",
    "UNIC.JK",
    "UNIQ.JK",
    "UNIT.JK",
    "UNSP.JK",
    "UNTR.JK",
    "UNVR.JK",
    "URBN.JK",
    "URI.JK",
    "URL.JK",
    "UTC.JK",
    "UTF.JK", 
    "UVCR.JK",
    "VAST.JK",
    "VERN.JK",
    "VICI.JK",
    "VICO.JK",
    "VINS.JK",
    "VISI.JK",
    "VIVA.JK",
    "VKTR.JK",
    "VOKS.JK",
    "VRNA.JK",
    "WAPO.JK", 
    "WEGE.JK",
    "WEHA.JK",
    "WGSH.JK",
    "WICO.JK",
    "WIDI.JK",
    "WIFI.JK",
    "WIIM.JK",
    "WIKA.JK",
    "WINR.JK",
    "WINS.JK",
    "WIR.JK",
    "WIRG.JK", 
    "WMEP.JK",
    "WMES.JK",
    "WMPP.JK",
    "WMUU.JK",
    "WOMF.JK",
    "WOOD.JK",
    "WOWS.JK",
    "WSBP.JK",
    "WSKT.JK",
    "WTON.JK",
    "YELO.JK",
    "YPAS.JK", 
    "YULE.JK",
    "ZATA.JK",
    "ZBRA.JK",
    "ZINC.JK",
    "ZONE.JK",
    "ZYRX.JK",
]

# =========================
# UTILS
# =========================

def safe_yf_download(*args, **kwargs):
    """Redir stdout/stderr supaya '1 Failed download' tidak muncul."""
    buf = io.StringIO()
    with contextlib.redirect_stdout(buf), contextlib.redirect_stderr(buf):
        try:
            df = yf.download(*args, **kwargs)
        except Exception:
            return None
    if df is None or df.empty:
        return None
    return df

def normalize_df(df: pd.DataFrame) -> pd.DataFrame:
    if df is None:
        return df
    if isinstance(df.columns, pd.MultiIndex):
        df.columns = [c[0] for c in df.columns]
    return df

def get_col(df: pd.DataFrame, name: str) -> pd.Series:
    if (df is None) or (name not in df.columns):
        return pd.Series(index=df.index, dtype=float)
    col = df[name]
    if isinstance(col, pd.DataFrame):
        col = col.iloc[:, 0]
    return col

def download_daily(symbol: str, period: str = PERIOD_DAILY):
    df = safe_yf_download(
        tickers=symbol,
        period=period,
        interval="1d",
        auto_adjust=False,
        progress=False,
    )
    if df is None:
        return None
    df = normalize_df(df)
    if df.index.tz is not None:
        df.index = df.index.tz_localize(None)

    # Khusus .JK: volume di yfinance biasanya per LOT → ubah ke lembar
    if symbol.endswith(".JK") and "Volume" in df.columns:
        df["Volume"] = df["Volume"] * 100

    return df.dropna(how="any")

# =========================
# CORE LOGIC
# =========================

def scan_symbol_volume_3x_ma10(symbol: str):
    """
    Return dict info kalau saham ini memenuhi:
    volume hari ini >= 3x MA10 volume.
    Kalau tidak memenuhi / data kurang, return None.
    """
    daily = download_daily(symbol)
    if daily is None or daily.empty:
        return None
    # print(daily)
    volume = get_col(daily, "Volume").astype(float)
    close  = get_col(daily, "Close").astype(float)

    if len(volume) < 10:
        return None

    vol_ma10 = volume.rolling(10).mean()
    last_idx  = volume.index[-1]
    last_vol  = float(volume.iloc[-1])
    last_ma10 = float(vol_ma10.iloc[-1])

    # kalau MA10 = 0 (saham baru banget / tidur), skip
    if last_ma10 <= 0:
        return None

    ratio = last_vol / last_ma10

    if ratio >= 3.0:
        return {
            "symbol": symbol,
            "date": last_idx.strftime("%Y-%m-%d"),
            "close": float(close.iloc[-1]),
            "volume": int(last_vol),
            "vol_ma10": int(last_ma10),
            "ratio": float(ratio),
        }
    return None

def main():
    print("=== Volume 3x MA10 Scanner ===")
    print(f"Run at: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print("Kriteria: Volume hari ini >= 3x rata-rata volume 10 hari terakhir (MA10)\n")

    hits = []

    for sym in UNIVERSE:
        try:
            info = scan_symbol_volume_3x_ma10(sym)
            if info is not None:
                hits.append(info)
        except Exception:
            # biar gak ganggu, langsung lanjut
            continue

    if not hits:
        print("Tidak ada saham yang memenuhi kriteria hari ini.")
        return

    df = pd.DataFrame(hits)
    # urutkan dari ratio terbesar
    df = df.sort_values("ratio", ascending=False)

    # print hasil ringkas
    print(f"Ditemukan {len(df)} saham:")
    print("-" * 80)
    for _, row in df.iterrows():
        print(
            f"{row['symbol']:8s} | "
            f"date={row['date']} | "
            f"close={row['close']:,.2f} | "
            f"vol={row['volume']:,} | "
            f"ma10={row['vol_ma10']:,} | "
            f"ratio={row['ratio']:.2f}x"
        )
    print("-" * 80)

    # kalau mau simpan ke CSV:
    # df.to_csv("volume_3x_ma10_scan.csv", index=False)

if __name__ == "__main__":
    main()
